print('\n-----------------------------\n使用方法sort()对列表进行按字母顺序永久排列')
cars = ['bmw','audi','toyota','subaru']
cars.sort()
print(cars)
print('\n-----------------------------\n使用方法sort(reverse=True)对列表进行按字母反序永久排列')
cars.sort(reverse=True)
print(cars)
print('\n-----------------------------\n使用函数sorted()对列表进行按字母顺序临时排列')
cars = ['bmw','audi','toyota','subaru']
print(cars)
print(sorted(cars))
print(cars)
print('\n-----------------------------\n使用函数sorted(reverse=True)对列表进行按字母反序临时排列??????')
cars = ['bmw','audi','toyota','subaru']
print(cars)
print(sorted(cars))
print(cars)
print('\n-----------------------------\n使用方法revers()对列表顺序进行永久反转')
cars = ['bmw','audi','toyota','subaru']
print(cars)
cars.reverse()
print(cars)
print('\n-----------------------------\n使用函数len()确定列表长度')
print(len(cars))
print('\n-----------------------------\n测试3-8')
favorite_place = ['hainan','yunnan','beijing','guilin']
print(favorite_place)
print(sorted(favorite_place))
print(favorite_place)
favorite_place.reverse()
print(favorite_place)
favorite_place.reverse()
print(favorite_place)
favorite_place.sort()
print(favorite_place)
favorite_place.sort(reverse=True)
print(favorite_place)
print(len(favorite_place))
